const gorog_1_dolgozat_1 =
{
    cim: "Görög 1 dolgozat 1",
    rajzolo: gorog_szokikerdezo,
    elemek:
    [
        {"gorog": "ὁ θεός, -οῦ",         "magyar": "Isten"},
        {"gorog": "ὁ λόγος, -ου",        "magyar": "szó, ige"},
        {"gorog": "τὸ δῶρον, -οῦ",       "magyar": "ajándék"},
        {"gorog": "ὁ κύριος, -ου",       "magyar": "úr"},
        {"gorog": "ὁ νόμος, -οῦ",        "magyar": "törvény"},
        {"gorog": "ποιέω",               "magyar": "tesz, csinál"},
        {"gorog": "ὁ ἀδελφός, -ου",      "magyar": "testvér"},
        {"gorog": "ἐσθιω",               "magyar": "eszik"},
        {"gorog": "ἡ ὁδός, -οῦ",         "magyar": "út"},
        {"gorog": "λύω",                 "magyar": "old"},
        {"gorog": "λαμβάνω",             "magyar": "kap, vesz"},
        {"gorog": "τὸ πλοῖον, -ου",      "magyar": "hajó, csónak"},
        {"gorog": "κηρύσσω",             "magyar": "hirdet, prédikál"},
        {"gorog": "τὸ τέκνον, -ου",      "magyar": "gyermek"},
        {"gorog": "τὸ ἔργον, -ου",       "magyar": "munka, mű, cselekedet"},
        {"gorog": "ὁ δοῦλος, -ου",       "magyar": "rabszolga"},
        {"gorog": "λέγω",                "magyar": "mond"},
        {"gorog": "πιστεύω",             "magyar": "hisz, bízik"},
        {"gorog": "οὐ, οὐκ, οὐχ",        "magyar": "nem (tagadás)"},
        {"gorog": "γράφω",               "magyar": "ír"},
        {"gorog": "παιδεύω",             "magyar": "nevel"},
        {"gorog": "τὸ εὐγγέλιον, -ου",   "magyar": "jó hír, örömüzenet"},
        {"gorog": "σώζω",                "magyar": "megment, üdvözít"},
        {"gorog": "βλέπω",               "magyar": "néz, megpillant"},
        {"gorog": "θεραπεύω",            "magyar": "gyógyít, gondoz, szolgál"},
        {"gorog": "τὸ δαιμόνιον, -ου",   "magyar": "démon (pl. ördög)"},
        {"gorog": "ὁ ἄρτος, -ου",        "magyar": "kenyér"},
        {"gorog": "εὑρίσκω",             "magyar": "talál"},
        {"gorog": "τὸ ἀργύριον, -ου",    "magyar": "ezüst pénz"},
        {"gorog": "ἀκούω",               "magyar": "hall"},
        {"gorog": "μαρτυρέω +D",         "magyar": "bizonyságot tesz valamiről"},
        {"gorog": "ὁ ἄγγελος, -ου",      "magyar": "követ, angyal"},
        {"gorog": "τὸ ἱμάτιον, -ου",     "magyar": "ruha, ruházat"},
    ]
};